name: Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Deps
        run: npm ci
      - name: Test
        run: npm run test:ci
